### PR TITLE
ENH: add pre-commit hooks yaml file

### LINKED ISSUE #46: ENH: pre-commit hook?
Would it be welcome if I added a `.pre-commit-hook.yaml` file, so this tool can be used as a pre-commit hook?

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #46

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
You can then use this as a pre-commit hook by making a file containing:
```
repos:
  - repo: https://github.com/s-weigand/flake8-nb
    rev: master  # replace with tag when this is released to PyPI
    hooks:
    - id: flake8-nb
```

**Comment by s-weigand** [comment]
Nice 😄 
Could you add https://github.com/s-weigand/flake8-nb/pull/47#issuecomment-660457495 to the docs [usage part](https://github.com/s-weigand/flake8-nb/blob/master/docs/usage.rst)?
After that I would make a new release.

**Comment by MarcoGorelli** [comment]
Sure! Will the new release be 0.1.9?

**Comment by s-weigand** [comment]
Maybe 0.2.0 would fit better since a feature got added

**Comment by MarcoGorelli** [comment]
sure, done

**Comment by s-weigand** [comment]
@all-contributors please add @MarcoGorelli  for tool doc

**Comment by MarcoGorelli** [comment]
Thanks @s-weigand - BTW, in case it's useful to you, I've also been working on a Jupyter Notebook code-quality tool: https://github.com/MarcoGorelli/nbQA

**Pull request merged**
